In [2]:
import pandas as pd
import datetime as dt
import pandas_datareader as pdr

In [11]:
company= "BAC"
start="2014-01-01"
end="2018-12-31"
df=pdr.DataReader(name=company,data_source='iex',start=start,end=end)

In [12]:
df.head

<bound method NDFrame.head of                open     high      low    close     volume
date
2014-01-13  15.6731  15.6824  15.3090  15.3370   90827849
2014-01-14  15.4397  15.6544  15.4304  15.6544   98517898
2014-01-15  16.0838  16.2612  15.9718  16.0091  330005943
2014-01-16  15.9531  15.9998  15.8598  15.9438  163879260
2014-01-17  16.0558  16.0745  15.8598  15.8785   96509703
2014-01-21  15.9438  16.0138  15.7478  15.8785  118388995
2014-01-22  15.9438  16.0091  15.8691  16.0091   68231534
2014-01-23  15.9345  15.9531  15.6264  15.7384  124037063
2014-01-24  15.5611  15.6077  15.3557  15.3557  114269725
2014-01-27  15.2810  15.4397  14.9917  15.2250  135060624
2014-01-28  15.3557  15.6451  15.2810  15.6171   93652513
2014-01-29  15.4491  15.7291  15.3931  15.5704  130381992
2014-01-30  15.6918  15.8598  15.6498  15.8038   91147776
2014-01-31  15.6077  15.8505  15.5051  15.6358  139608553
2014-02-03  15.6544  15.7571  15.2157  15.2624  160718806
2014-02-04  15.3931  15.4584  15.1784  15.2624  125833754
2014-02-05  15.2250  15.3557  15.0757  15.3090  110835126
2014-02-06  15.3557  15.6171  15.3464  15.5797  110229403
2014-02-07  15.7011  15.7571  15.5237  15.7011  151911622
2014-02-10  15.5984  15.6171  15.4957  15.6077   96136622
2014-02-11  15.6124  15.7944  15.5284  15.7571   92866298
2014-02-12  15.7478  15.7851  15.5424  15.6358   97286498
2014-02-13  15.5377  15.7011  15.5237  15.6358   96047289
2014-02-14  15.6264  15.6451  15.5424  15.5891  113375071
2014-02-18  15.5891  15.6264  15.3744  15.3744  122179187
2014-02-19  15.2904  15.3557  15.1037  15.1223  138080546
2014-02-20  15.1410  15.2717  15.1037  15.2157  107820954
2014-02-21  15.2064  15.3884  15.1690  15.2064  106622165
2014-02-24  15.2157  15.5237  15.2157  15.4304  103039579
2014-02-25  15.4024  15.4584  15.2344  15.2530   81617640
...             ...      ...      ...      ...        ...
2018-11-15  26.9892  27.8145  26.7306  27.7449   66174810
2018-11-16  27.5361  27.7350  27.2676  27.5958   52456146
2018-11-19  27.6256  27.8643  27.3869  27.5958   45999950
2018-11-20  27.2676  27.4168  26.8201  27.2278   92330608
2018-11-21  27.4367  27.6057  27.0985  27.1184   40364427
2018-11-23  26.9295  27.0190  26.7306  26.8201   22974139
2018-11-26  27.0289  27.5759  26.9494  27.4068   53210681
2018-11-27  27.2775  27.7449  27.2378  27.5858   43617082
2018-11-28  27.7250  28.3118  27.4068  28.2720   61388131
2018-11-29  28.0234  28.1924  27.8145  27.8842   46824634
2018-11-30  27.7847  28.4709  27.7151  28.2422   64284619
2018-12-03  28.8289  28.8736  28.1974  28.3814   59905121
2018-12-04  28.1626  28.1626  26.5814  26.8400  103565701
2018-12-06  26.2300  26.3200  25.5321  26.2800  133294174
2018-12-07  26.1500  26.5400  25.3000  25.4300  107477614
2018-12-10  25.1800  25.2300  24.2900  24.7600  110166901
2018-12-11  25.2100  25.4000  24.5300  24.5800   78545015
2018-12-12  24.8700  24.9900  24.3700  24.5200   87191846
2018-12-13  24.6600  24.8200  24.2800  24.4000   64860054
2018-12-14  24.1800  24.8700  24.1200  24.4800   92762595
2018-12-17  24.2600  24.9300  24.1600  24.4700   98602808
2018-12-18  24.6700  25.0900  24.3118  24.4700   89046306
2018-12-19  24.4500  25.2400  24.0700  24.1800  121887605
2018-12-20  23.8500  24.4250  23.7600  24.1100  112594029
2018-12-21  23.9100  24.5100  23.2600  23.3700  160800438
2018-12-24  22.7600  23.2100  22.6600  22.7300   64859064
2018-12-26  22.9100  24.1750  22.6900  24.1100  100877810
2018-12-27  23.7800  24.3700  23.3900  24.3700   91575402
2018-12-28  24.5900  24.7500  24.2600  24.3900   78693797
2018-12-31  24.5700  24.9700  24.3700  24.6400   56257342

[1251 rows x 5 columns]>

In [13]:
df.values

array([[1.56731000e+01, 1.56824000e+01, 1.53090000e+01, 1.53370000e+01,
        9.08278490e+07],
       [1.54397000e+01, 1.56544000e+01, 1.54304000e+01, 1.56544000e+01,
        9.85178980e+07],
       [1.60838000e+01, 1.62612000e+01, 1.59718000e+01, 1.60091000e+01,
        3.30005943e+08],
       ...,
       [2.37800000e+01, 2.43700000e+01, 2.33900000e+01, 2.43700000e+01,
        9.15754020e+07],
       [2.45900000e+01, 2.47500000e+01, 2.42600000e+01, 2.43900000e+01,
        7.86937970e+07],
       [2.45700000e+01, 2.49700000e+01, 2.43700000e+01, 2.46400000e+01,
        5.62573420e+07]])

In [14]:
df.columns

Index(['open', 'high', 'low', 'close', 'volume'], dtype='object')

In [15]:
df.index

Index(['2014-01-13', '2014-01-14', '2014-01-15', '2014-01-16', '2014-01-17',
       '2014-01-21', '2014-01-22', '2014-01-23', '2014-01-24', '2014-01-27',
       ...
       '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21',
       '2018-12-24', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-31'],
      dtype='object', name='date', length=1251)

In [17]:
df.axes

[Index(['2014-01-13', '2014-01-14', '2014-01-15', '2014-01-16', '2014-01-17',
        '2014-01-21', '2014-01-22', '2014-01-23', '2014-01-24', '2014-01-27',
        ...
        '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21',
        '2018-12-24', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-31'],
       dtype='object', name='date', length=1251),
 Index(['open', 'high', 'low', 'close', 'volume'], dtype='object')]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1251 entries, 2014-01-13 to 2018-12-31
Data columns (total 5 columns):
open      1251 non-null float64
high      1251 non-null float64
low       1251 non-null float64
close     1251 non-null float64
volume    1251 non-null int64
dtypes: float64(4), int64(1)
memory usage: 58.6+ KB

In [21]:
df['low'].describe()

count    1251.000000
mean       19.667529
std         6.091836
min        10.459700
25%        14.781850
50%        16.170100
75%        24.351850
max        32.171000
Name: low, dtype: float64

In [22]:
df.loc['2014-03-04']

open      1.538370e+01
high      1.562640e+01
low       1.533700e+01
close     1.561710e+01
volume    1.017019e+08
Name: 2014-03-04, dtype: float64

In [23]:
df.iloc[300]

open      1.483650e+01
high      1.490250e+01
low       1.472330e+01
close     1.472330e+01
volume    7.701098e+07
Name: 2015-03-24, dtype: float64

In [27]:
df.loc['2014-10-01':'2015-10-07'].head

<bound method NDFrame.head of                open     high      low    close     volume
date
2014-10-01  16.0034  16.0222  15.7503  15.7690   91235935
2014-10-02  15.8065  15.9284  15.5909  15.8253  118018774
2014-10-03  16.0409  16.2191  15.9940  16.2097  110840569
2014-10-06  16.2847  16.3222  16.1441  16.2097   66212066
2014-10-07  16.1065  16.1253  15.8253  15.8253   91396327
2014-10-08  15.8253  16.0503  15.6753  16.0503  101266804
2014-10-09  15.9753  16.0409  15.5159  15.5534  121363088
2014-10-10  15.4878  15.7222  15.3378  15.4503  129552650
2014-10-13  15.4503  15.6284  15.3753  15.3753   92674130
2014-10-14  15.4784  15.5909  15.3378  15.4878   97451881
2014-10-15  15.2159  15.2253  14.4659  14.7753  216591804
2014-10-16  14.6346  15.2347  14.5503  15.0753  148199432
2014-10-17  15.2347  15.3847  15.1503  15.1972   94339180
2014-10-20  15.1878  15.3097  15.1503  15.2440   76510730
2014-10-21  15.4034  15.5722  15.2909  15.5628   78287334
2014-10-22  15.5534  15.6565  15.3472  15.3753   85199795
2014-10-23  15.5440  15.6847  15.4831  15.5628   68436551
2014-10-24  15.5909  15.6753  15.5253  15.6753   41951414
2014-10-27  15.6378  15.6472  15.4690  15.5534   51499970
2014-10-28  15.5815  15.7503  15.5722  15.7503   71850839
2014-10-29  15.7222  15.9565  15.6659  15.9284   99875657
2014-10-30  15.9003  16.0503  15.7878  15.9659   72579120
2014-10-31  16.0972  16.1441  16.0315  16.0878   82788923
2014-11-03  16.1065  16.2659  16.0315  16.1909   64109402
2014-11-04  16.1441  16.2191  15.9565  16.1347   53515435
2014-11-05  16.2378  16.2847  16.1347  16.2566   58608232
2014-11-06  16.2566  16.3128  16.2003  16.2753   57339203
2014-11-07  16.2284  16.2941  16.1441  16.2753   53907826
2014-11-10  16.2753  16.3128  16.2191  16.2847   54261121
2014-11-11  16.2847  16.3691  16.2191  16.2378   62236029
...             ...      ...      ...      ...        ...
2015-08-26  14.9567  15.1932  14.5073  15.1932  174208534
2015-08-27  15.4959  15.5621  15.2216  15.5527  124185443
2015-08-28  15.5148  15.5527  15.3256  15.4770   75899306
2015-08-31  15.4486  15.4912  15.3067  15.4581   66695185
2015-09-01  15.0891  15.1837  14.6256  14.7391  119064035
2015-09-02  15.0048  15.0523  14.7771  15.0428   74820399
2015-09-03  15.1567  15.3654  15.0618  15.1282   77175757
2015-09-04  14.9859  15.0523  14.7106  14.8530  104539500
2015-09-08  15.1472  15.3370  15.0903  15.3370   73960238
2015-09-09  15.5363  15.6217  15.0238  15.0903   70466139
2015-09-10  15.0618  15.2896  15.0048  15.2231   71110193
2015-09-11  15.1757  15.2421  15.0903  15.2231   54287677
2015-09-14  15.1567  15.2516  15.0903  15.1472   50640946
2015-09-15  15.2231  15.5553  15.1947  15.4794   62327105
2015-09-16  15.5173  15.5553  15.2706  15.4984   83776419
2015-09-17  15.4604  15.6407  14.9764  15.0523  119088186
2015-09-18  14.8815  14.9099  14.7106  14.7676  136531198
2015-09-21  14.8720  14.9479  14.7771  14.9004   79096205
2015-09-22  14.7011  14.7866  14.6632  14.7771   92235195
2015-09-23  14.8055  15.0428  14.7866  14.9194   78117507
2015-09-24  14.7438  14.8245  14.6157  14.7581   99520125
2015-09-25  15.0713  15.2041  15.0048  15.0808   88654983
2015-09-28  14.9859  15.0143  14.5967  14.6822   91324283
2015-09-29  14.7106  14.7391  14.4734  14.5683   79829410
2015-09-30  14.7581  14.8055  14.5398  14.7866   71347084
2015-10-01  14.7296  14.8435  14.5778  14.7581   71516846
2015-10-02  14.3120  14.5967  13.8849  14.5967  181838369
2015-10-05  14.6632  14.9859  14.6537  14.8909   75315340
2015-10-06  14.8815  15.0143  14.7771  14.8909   67473718
2015-10-07  14.9764  15.1187  14.7771  14.9479   67019915

[257 rows x 5 columns]>

In [32]:
cumples=pd.date_range(start='1984-09-05',end='2018-12-31', freq=pd.DateOffset(years=1))

In [31]:
len(pd.date_range(start='1984-09-05',end='2018-12-31', freq=pd.DateOffset(years=1)))

35

In [33]:
df.index.isin(cumples)

array([False, False, False, ..., False, False, False])

In [34]:
mascara=df.index.isin(cumples)

In [40]:
esta=df.loc[mascara]
esta.info

<bound method DataFrame.info of Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []>