In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
w1=pd.read_csv("csvs/Restaurant - Week 1 Sales.csv")
w2=pd.read_csv("csvs/Restaurant - Week 2 Sales.csv")
ct=pd.read_csv("csvs/Restaurant - Customers.csv",index_col='ID')
fot=pd.read_csv("csvs/Restaurant - Foods.csv",index_col='Food ID')
we=pd.read_csv("csvs/Restaurant - Week 1 Satisfaction.csv")
fot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 1 to 10
Data columns (total 2 columns):
Food Item    10 non-null object
Price        10 non-null float64
dtypes: float64(1), object(1)
memory usage: 240.0+ bytes

In [3]:
we.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 1 columns):
Satisfaction Rating    250 non-null int64
dtypes: int64(1)
memory usage: 2.0 KB

In [5]:
w1.join(we).head

<bound method NDFrame.head of      Customer ID  Food ID  Satisfaction Rating
0            537        9                    2
1             97        4                    7
2            658        1                    3
3            202        2                    7
4            155        9                   10
5            213        8                    3
6            600        1                    2
7            503        5                    5
8             71        3                   10
9            174        3                    7
10           961        9                    7
11           966        5                    5
12           641        4                    3
13           288        2                    2
14           149        4                    7
15           954        2                    4
16           147        9                    6
17           155        1                    1
18           550        6                    5
19           101        7                    5
20           549        6                    3
21            75        6                    2
22            78        7                    3
23           514        5                   10
24           833        7                    4
25           329        8                    9
26           586       10                    1
27           341        1                    4
28           519       10                    4
29           680        9                    9
..           ...      ...                  ...
220          147        8                    3
221          745        4                    8
222          184        3                    4
223          828        8                    2
224          578        5                    5
225          491        4                    2
226           62        4                    6
227           77        9                    4
228          506        9                    9
229          271        9                    2
230          584       10                    4
231          148        5                    8
232          595        3                    4
233          274       10                    2
234          646        1                    9
235          520        8                    4
236          644        8                    6
237          725        8                    6
238          934        4                    7
239          151       10                   10
240          945        5                    8
241          343        3                    1
242          380        9                    2
243          911        4                    8
244          621        9                    2
245          413        9                    1
246          926        6                    2
247          134        3                    8
248          396        6                   10
249          535       10                    3

[250 rows x 3 columns]>

In [6]:
pd.merge(w1,ct,how='left',left_on='Customer ID',right_on='ID')

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Customer ID</th>
      <th>Food ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Gender</th>
      <th>Company</th>
      <th>Occupation</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>537</td>
      <td>9</td>
      <td>Cheryl</td>
      <td>Carroll</td>
      <td>Female</td>
      <td>Zoombeat</td>
      <td>Registered Nurse</td>
    </tr>
    <tr>
      <th>1</th>
      <td>97</td>
      <td>4</td>
      <td>Amanda</td>
      <td>Watkins</td>
      <td>Female</td>
      <td>Ozu</td>
      <td>Account Coordinator</td>
    </tr>
    <tr>
      <th>2</th>
      <td>658</td>
      <td>1</td>
      <td>Patrick</td>
      <td>Webb</td>
      <td>Male</td>
      <td>Browsebug</td>
      <td>Community Outreach Specialist</td>
    </tr>
    <tr>
      <th>3</th>
      <td>202</td>
      <td>2</td>
      <td>Louis</td>
      <td>Campbell</td>
      <td>Male</td>
      <td>Rhynoodle</td>
      <td>Account Representative III</td>
    </tr>
    <tr>
      <th>4</th>
      <td>155</td>
      <td>9</td>
      <td>Carolyn</td>
      <td>Diaz</td>
      <td>Female</td>
      <td>Gigazoom</td>
      <td>Database Administrator III</td>
    </tr>
    <tr>
      <th>5</th>
      <td>213</td>
      <td>8</td>
      <td>Keith</td>
      <td>Foster</td>
      <td>Male</td>
      <td>Gigashots</td>
      <td>VP Quality Control</td>
    </tr>
    <tr>
      <th>6</th>
      <td>600</td>
      <td>1</td>
      <td>Sandra</td>
      <td>Bailey</td>
      <td>Female</td>
      <td>Jaxnation</td>
      <td>Sales Associate</td>
    </tr>
    <tr>
      <th>7</th>
      <td>503</td>
      <td>5</td>
      <td>Justin</td>
      <td>Daniels</td>
      <td>Male</td>
      <td>Oloo</td>
      <td>Environmental Tech</td>
    </tr>
    <tr>
      <th>8</th>
      <td>71</td>
      <td>3</td>
      <td>Carolyn</td>
      <td>Reyes</td>
      <td>Female</td>
      <td>Twimbo</td>
      <td>Safety Technician IV</td>
    </tr>
    <tr>
      <th>9</th>
      <td>174</td>
      <td>3</td>
      <td>Anna</td>
      <td>Miller</td>
      <td>Female</td>
      <td>Innojam</td>
      <td>Developer I</td>
    </tr>
    <tr>
      <th>10</th>
      <td>961</td>
      <td>9</td>
      <td>Ralph</td>
      <td>Richards</td>
      <td>Male</td>
      <td>Thoughtstorm</td>
      <td>Accountant I</td>
    </tr>
    <tr>
      <th>11</th>
      <td>966</td>
      <td>5</td>
      <td>Robert</td>
      <td>Ford</td>
      <td>Male</td>
      <td>Jabbertype</td>
      <td>Account Representative IV</td>
    </tr>
    <tr>
      <th>12</th>
      <td>641</td>
      <td>4</td>
      <td>Donna</td>
      <td>Gutierrez</td>
      <td>Female</td>
      <td>Dabtype</td>
      <td>Assistant Professor</td>
    </tr>
    <tr>
      <th>13</th>
      <td>288</td>
      <td>2</td>
      <td>Kenneth</td>
      <td>Jackson</td>
      <td>Male</td>
      <td>Voomm</td>
      <td>Associate Professor</td>
    </tr>
    <tr>
      <th>14</th>
      <td>149</td>
      <td>4</td>
      <td>Jennifer</td>
      <td>Oliver</td>
      <td>Female</td>
      <td>Topiclounge</td>
      <td>Database Administrator III</td>
    </tr>
    <tr>
      <th>15</th>
      <td>954</td>
      <td>2</td>
      <td>Thomas</td>
      <td>Perkins</td>
      <td>Male</td>
      <td>Roodel</td>
      <td>Account Executive</td>
    </tr>
    <tr>
      <th>16</th>
      <td>147</td>
      <td>9</td>
      <td>Theresa</td>
      <td>Morales</td>
      <td>Female</td>
      <td>Abata</td>
      <td>Occupational Therapist</td>
    </tr>
    <tr>
      <th>17</th>
      <td>155</td>
      <td>1</td>
      <td>Carolyn</td>
      <td>Diaz</td>
      <td>Female</td>
      <td>Gigazoom</td>
      <td>Database Administrator III</td>
    </tr>
    <tr>
      <th>18</th>
      <td>550</td>
      <td>6</td>
      <td>Walter</td>
      <td>Miller</td>
      <td>Male</td>
      <td>Yata</td>
      <td>Payment Adjustment Coordinator</td>
    </tr>
    <tr>
      <th>19</th>
      <td>101</td>
      <td>7</td>
      <td>Jeremy</td>
      <td>Nelson</td>
      <td>Male</td>
      <td>Brainlounge</td>
      <td>Web Developer IV</td>
    </tr>
    <tr>
      <th>20</th>
      <td>549</td>
      <td>6</td>
      <td>Harold</td>
      <td>Rivera</td>
      <td>Male</td>
      <td>Topdrive</td>
      <td>Cost Accountant</td>
    </tr>
    <tr>
      <th>21</th>
      <td>75</td>
      <td>6</td>
      <td>Catherine</td>
      <td>Carpenter</td>
      <td>Female</td>
      <td>Zoozzy</td>
      <td>Marketing Manager</td>
    </tr>
    <tr>
      <th>22</th>
      <td>78</td>
      <td>7</td>
      <td>Robert</td>
      <td>Kennedy</td>
      <td>Male</td>
      <td>Edgewire</td>
      <td>Chemical Engineer</td>
    </tr>
    <tr>
      <th>23</th>
      <td>514</td>
      <td>5</td>
      <td>Jack</td>
      <td>Hill</td>
      <td>Male</td>
      <td>Blogtags</td>
      <td>Assistant Professor</td>
    </tr>
    <tr>
      <th>24</th>
      <td>833</td>
      <td>7</td>
      <td>Carolyn</td>
      <td>Dunn</td>
      <td>Female</td>
      <td>Yadel</td>
      <td>Recruiter</td>
    </tr>
    <tr>
      <th>25</th>
      <td>329</td>
      <td>8</td>
      <td>Amanda</td>
      <td>Nguyen</td>
      <td>Female</td>
      <td>Meezzy</td>
      <td>Associate Professor</td>
    </tr>
    <tr>
      <th>26</th>
      <td>586</td>
      <td>10</td>
      <td>Doris</td>
      <td>Mcdonald</td>
      <td>Female</td>
      <td>Youfeed</td>
      <td>Marketing Assistant</td>
    </tr>
    <tr>
      <th>27</th>
      <td>341</td>
      <td>1</td>
      <td>Rachel</td>
      <td>Robinson</td>
      <td>Female</td>
      <td>Twinder</td>
      <td>Safety Technician IV</td>
    </tr>
    <tr>
      <th>28</th>
      <td>519</td>
      <td>10</td>
      <td>Lillian</td>
      <td>Rogers</td>
      <td>Female</td>
      <td>Eazzy</td>
      <td>Paralegal</td>
    </tr>
    <tr>
      <th>29</th>
      <td>680</td>
      <td>9</td>
      <td>Irene</td>
      <td>Gordon</td>
      <td>Female</td>
      <td>Voolith</td>
      <td>Database Administrator II</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>220</th>
      <td>147</td>
      <td>8</td>
      <td>Theresa</td>
      <td>Morales</td>
      <td>Female</td>
      <td>Abata</td>
      <td>Occupational Therapist</td>
    </tr>
    <tr>
      <th>221</th>
      <td>745</td>
      <td>4</td>
      <td>Nicole</td>
      <td>Garza</td>
      <td>Female</td>
      <td>Topiczoom</td>
      <td>General Manager</td>
    </tr>
    <tr>
      <th>222</th>
      <td>184</td>
      <td>3</td>
      <td>Jesse</td>
      <td>Edwards</td>
      <td>Male</td>
      <td>Zoombeat</td>
      <td>Administrative Officer</td>
    </tr>
    <tr>
      <th>223</th>
      <td>828</td>
      <td>8</td>
      <td>Mary</td>
      <td>Payne</td>
      <td>Female</td>
      <td>Oyonder</td>
      <td>Assistant Media Planner</td>
    </tr>
    <tr>
      <th>224</th>
      <td>578</td>
      <td>5</td>
      <td>Donald</td>
      <td>Matthews</td>
      <td>Male</td>
      <td>Fiveclub</td>
      <td>Physical Therapy Assistant</td>
    </tr>
    <tr>
      <th>225</th>
      <td>491</td>
      <td>4</td>
      <td>Anna</td>
      <td>Perkins</td>
      <td>Female</td>
      <td>Zazio</td>
      <td>Quality Engineer</td>
    </tr>
    <tr>
      <th>226</th>
      <td>62</td>
      <td>4</td>
      <td>Andrew</td>
      <td>Tucker</td>
      <td>Male</td>
      <td>Leenti</td>
      <td>Structural Analysis Engineer</td>
    </tr>
    <tr>
      <th>227</th>
      <td>77</td>
      <td>9</td>
      <td>Lori</td>
      <td>Edwards</td>
      <td>Female</td>
      <td>Dabvine</td>
      <td>Sales Representative</td>
    </tr>
    <tr>
      <th>228</th>
      <td>506</td>
      <td>9</td>
      <td>Mildred</td>
      <td>Mendoza</td>
      <td>Female</td>
      <td>Vitz</td>
      <td>Environmental Tech</td>
    </tr>
    <tr>
      <th>229</th>
      <td>271</td>
      <td>9</td>
      <td>Beverly</td>
      <td>Ward</td>
      <td>Female</td>
      <td>Brainbox</td>
      <td>Automation Specialist II</td>
    </tr>
    <tr>
      <th>230</th>
      <td>584</td>
      <td>10</td>
      <td>Jeffrey</td>
      <td>Simmons</td>
      <td>Male</td>
      <td>Flipstorm</td>
      <td>Chemical Engineer</td>
    </tr>
    <tr>
      <th>231</th>
      <td>148</td>
      <td>5</td>
      <td>Patricia</td>
      <td>Reid</td>
      <td>Female</td>
      <td>Shuffledrive</td>
      <td>Analog Circuit Design manager</td>
    </tr>
    <tr>
      <th>232</th>
      <td>595</td>
      <td>3</td>
      <td>Bruce</td>
      <td>Kennedy</td>
      <td>Male</td>
      <td>Mydo</td>
      <td>Recruiter</td>
    </tr>
    <tr>
      <th>233</th>
      <td>274</td>
      <td>10</td>
      <td>Gary</td>
      <td>Reid</td>
      <td>Male</td>
      <td>Fivespan</td>
      <td>Executive Secretary</td>
    </tr>
    <tr>
      <th>234</th>
      <td>646</td>
      <td>1</td>
      <td>Wanda</td>
      <td>Lane</td>
      <td>Female</td>
      <td>Twiyo</td>
      <td>Help Desk Technician</td>
    </tr>
    <tr>
      <th>235</th>
      <td>520</td>
      <td>8</td>
      <td>Melissa</td>
      <td>Wallace</td>
      <td>Female</td>
      <td>Skyvu</td>
      <td>Administrative Officer</td>
    </tr>
    <tr>
      <th>236</th>
      <td>644</td>
      <td>8</td>
      <td>Louis</td>
      <td>Brooks</td>
      <td>Male</td>
      <td>Nlounge</td>
      <td>VP Quality Control</td>
    </tr>
    <tr>
      <th>237</th>
      <td>725</td>
      <td>8</td>
      <td>Carol</td>
      <td>Russell</td>
      <td>Female</td>
      <td>BlogXS</td>
      <td>Pharmacist</td>
    </tr>
    <tr>
      <th>238</th>
      <td>934</td>
      <td>4</td>
      <td>Joseph</td>
      <td>Burton</td>
      <td>Male</td>
      <td>Leexo</td>
      <td>Compensation Analyst</td>
    </tr>
    <tr>
      <th>239</th>
      <td>151</td>
      <td>10</td>
      <td>Brandon</td>
      <td>Oliver</td>
      <td>Male</td>
      <td>Voomm</td>
      <td>Internal Auditor</td>
    </tr>
    <tr>
      <th>240</th>
      <td>945</td>
      <td>5</td>
      <td>Anne</td>
      <td>Reed</td>
      <td>Female</td>
      <td>Twitterworks</td>
      <td>Director of Sales</td>
    </tr>
    <tr>
      <th>241</th>
      <td>343</td>
      <td>3</td>
      <td>Joe</td>
      <td>Price</td>
      <td>Male</td>
      <td>Fanoodle</td>
      <td>Marketing Manager</td>
    </tr>
    <tr>
      <th>242</th>
      <td>380</td>
      <td>9</td>
      <td>Martha</td>
      <td>Payne</td>
      <td>Female</td>
      <td>Quinu</td>
      <td>Assistant Media Planner</td>
    </tr>
    <tr>
      <th>243</th>
      <td>911</td>
      <td>4</td>
      <td>Patrick</td>
      <td>Reed</td>
      <td>Male</td>
      <td>Jabberstorm</td>
      <td>Senior Quality Engineer</td>
    </tr>
    <tr>
      <th>244</th>
      <td>621</td>
      <td>9</td>
      <td>Amy</td>
      <td>Long</td>
      <td>Female</td>
      <td>Skidoo</td>
      <td>Research Associate</td>
    </tr>
    <tr>
      <th>245</th>
      <td>413</td>
      <td>9</td>
      <td>Diane</td>
      <td>Bailey</td>
      <td>Female</td>
      <td>Wikibox</td>
      <td>Technical Writer</td>
    </tr>
    <tr>
      <th>246</th>
      <td>926</td>
      <td>6</td>
      <td>Anne</td>
      <td>Wagner</td>
      <td>Female</td>
      <td>Skyba</td>
      <td>Legal Assistant</td>
    </tr>
    <tr>
      <th>247</th>
      <td>134</td>
      <td>3</td>
      <td>Diana</td>
      <td>Hall</td>
      <td>Female</td>
      <td>Quinu</td>
      <td>Financial Advisor</td>
    </tr>
    <tr>
      <th>248</th>
      <td>396</td>
      <td>6</td>
      <td>Juan</td>
      <td>Romero</td>
      <td>Male</td>
      <td>Zoonder</td>
      <td>Analyst Programmer</td>
    </tr>
    <tr>
      <th>249</th>
      <td>535</td>
      <td>10</td>
      <td>Nancy</td>
      <td>Cox</td>
      <td>Female</td>
      <td>Trudeo</td>
      <td>Research Associate</td>
    </tr>
  </tbody>
</table>
<p>250 rows × 7 columns</p>
</div>