In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import pandas_datareader as data
from pandas.tseries.offsets import *
start="2014-01-01"
end="2018-12-31"
companie=['MSFT','BAC','AAPL','FB','AMZN']
p=data.DataReader(name=companie,data_source='iex',start=start,end=end)
p.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1251 entries, 2014-01-13 to 2018-12-31
Data columns (total 25 columns):
(open, AAPL)      1251 non-null float64
(open, AMZN)      1251 non-null float64
(open, BAC)       1251 non-null float64
(open, FB)        1251 non-null float64
(open, MSFT)      1251 non-null float64
(high, AAPL)      1251 non-null float64
(high, AMZN)      1251 non-null float64
(high, BAC)       1251 non-null float64
(high, FB)        1251 non-null float64
(high, MSFT)      1251 non-null float64
(low, AAPL)       1251 non-null float64
(low, AMZN)       1251 non-null float64
(low, BAC)        1251 non-null float64
(low, FB)         1251 non-null float64
(low, MSFT)       1251 non-null float64
(close, AAPL)     1251 non-null float64
(close, AMZN)     1251 non-null float64
(close, BAC)      1251 non-null float64
(close, FB)       1251 non-null float64
(close, MSFT)     1251 non-null float64
(volume, AAPL)    1251 non-null int64
(volume, AMZN)    1251 non-null int64
(volume, BAC)     1251 non-null int64
(volume, FB)      1251 non-null int64
(volume, MSFT)    1251 non-null int64
dtypes: float64(20), int64(5)
memory usage: 254.1+ KB

In [7]:
p.axes

[Index(['2014-01-13', '2014-01-14', '2014-01-15', '2014-01-16', '2014-01-17',
        '2014-01-21', '2014-01-22', '2014-01-23', '2014-01-24', '2014-01-27',
        ...
        '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21',
        '2018-12-24', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-31'],
       dtype='object', name='date', length=1251),
 MultiIndex(levels=[['open', 'high', 'low', 'close', 'volume'], ['AAPL', 'AMZN', 'BAC', 'FB', 'MSFT']],
            labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
            names=['Attributes', 'Symbols'])]

In [17]:
p.head

<bound method NDFrame.head of Attributes      open                                           high  \
Symbols         AAPL      AMZN      BAC      FB      MSFT      AAPL
date
2014-01-13   69.4767   397.980  15.6731   57.91   31.9142   71.1274
2014-01-14   70.5663   392.130  15.4397   56.46   30.7969   71.6820
2014-01-15   72.5722   398.940  16.0838   57.98   31.8343   73.4481
2014-01-16   72.7532   393.680  15.9531   57.26   32.5349   73.0088
2014-01-17   72.3048   394.260  16.0558   57.30   32.6590   72.3821
2014-01-21   70.9294   403.000  15.9438   56.60   32.6502   72.1199
2014-01-22   72.2307   408.000  15.9438   58.85   32.1536   73.0665
2014-01-23   72.1029   401.000  15.9345   56.37   32.0028   72.9630
2014-01-24   72.6352   398.160  15.5611   56.15   33.2088   72.8476
2014-01-27   72.1199   390.500  15.2810   54.73   32.6945   72.7401
2014-01-28   66.7037   387.400  15.3557   54.02   32.0294   67.5219
2014-01-29   66.0731   392.160  15.4491   54.61   31.9053   66.5215
2014-01-30   65.8882   393.770  15.6918   62.12   32.6236   66.4074
2014-01-31   64.9233   371.760  15.6077   60.47   32.7654   65.7558
2014-02-03   65.8974   358.980  15.6544   63.03   33.4660   66.5687
2014-02-04   66.3222   349.590  15.3931   62.05   32.7832   66.7955
2014-02-05   66.4153   346.000  15.2250   62.74   32.1802   67.5586
2014-02-06   67.2745   347.403  15.3557   61.46   31.7457   67.7282
2014-02-07   68.7675   358.980  15.7011   62.27   32.2068   68.9720
2014-02-10   68.4088   361.610  15.5984   64.30   32.4817   70.1669
2014-02-11   69.9849   361.842  15.6124   63.75   32.7034   70.9266
2014-02-12   70.8211   356.430  15.7478   64.92   33.1201   71.1654
2014-02-13   70.5191   347.700  15.5377   64.18   33.1024   71.8631
2014-02-14   71.5492   359.340  15.6264   67.50   33.1556   72.0121
2014-02-18   72.0148   355.280  15.5891   66.94   33.6187   72.6993
2014-02-19   71.8499   352.640  15.2904   67.05   33.2524   72.1322
2014-02-20   70.2988   348.800  15.1410   67.73   33.5650   70.8277
2014-02-21   70.2728   352.440  15.2064   69.69   33.8956   70.5072
2014-02-24   69.0010   345.190  15.2157   68.74   33.6723   69.8939
2014-02-25   69.8227   353.000  15.4024   70.95   33.6008   69.8471
...              ...       ...      ...     ...       ...       ...
2018-11-15  188.3900  1581.010  26.9892  142.33  104.9900  191.9700
2018-11-16  190.5000  1587.500  27.5361  141.07  107.0800  194.9695
2018-11-19  190.0000  1577.010  27.6256  137.61  108.2700  190.7000
2018-11-20  178.3700  1437.500  27.2676  127.03  101.8000  181.4700
2018-11-21  179.7300  1542.990  27.4367  134.40  103.6000  180.2700
2018-11-23  174.9400  1517.000  26.9295  133.65  102.1700  176.5950
2018-11-26  174.2400  1539.000  27.0289  133.00  104.7900  174.9500
2018-11-27  171.5100  1575.990  27.2775  135.75  106.2700  174.7700
2018-11-28  176.7300  1613.920  27.7250  136.28  107.8900  181.2900
2018-11-29  182.6600  1674.990  28.0234  135.92  110.3300  182.8000
2018-11-30  180.2900  1679.500  27.7847  138.26  110.7000  180.3300
2018-12-03  184.4600  1769.460  28.8289  143.00  113.0000  184.9400
2018-12-04  180.9500  1756.000  28.1626  140.73  111.9400  182.3899
2018-12-06  171.7600  1614.870  26.2300  133.82  105.8200  174.7800
2018-12-07  173.4900  1705.070  26.1500  139.25  108.3800  174.4900
2018-12-10  165.0000  1623.840  25.1800  139.60  104.8000  170.0900
2018-12-11  171.6600  1678.000  25.2100  143.88  109.8000  171.7900
2018-12-12  170.4000  1669.000  24.8700  143.08  110.8900  171.9200
2018-12-13  170.4900  1680.000  24.6600  145.57  109.5800  172.5700
2018-12-14  169.0000  1638.000  24.1800  143.34  108.2500  169.0800
2018-12-17  165.4500  1566.000  24.2600  143.08  105.4100  168.3500
2018-12-18  165.3800  1540.000  24.6700  141.08  103.7500  167.5300
2018-12-19  166.0000  1543.050  24.4500  141.21  103.6500  167.4500
2018-12-20  160.4000  1484.000  23.8500  130.70  103.0500  162.1100
2018-12-21  156.8600  1464.990  23.9100  133.39  101.6300  158.1600
2018-12-24  148.1500  1346.000  22.7600  123.10   97.6800  151.5500
2018-12-26  148.3000  1368.890  22.9100  126.00   95.1400  157.2300
2018-12-27  155.8400  1454.200  23.7800  132.44   99.3000  156.7700
2018-12-28  157.5000  1473.350  24.5900  135.34  102.0900  158.5200
2018-12-31  158.5300  1510.800  24.5700  134.45  101.2900  159.3600

Attributes                                            ...         close  \
Symbols          AMZN      BAC        FB      MSFT    ...          AAPL
date                                                  ...
2014-01-13   399.7800  15.6824   58.2500   31.9408    ...       70.2398
2014-01-14   398.6300  15.6544   57.7800   31.8166    ...       71.6374
2014-01-15   399.3100  16.2612   58.5700   32.6236    ...       73.0757
2014-01-16   399.2900  15.9998   58.0200   32.8098    ...       72.6680
2014-01-17   403.4900  16.0745   57.8200   32.6590    ...       70.8875
2014-01-21   407.8000  16.0138   58.5800   32.6502    ...       71.9888
2014-01-22   408.0600  16.0091   59.3100   32.2068    ...       72.3087
2014-01-23   406.1700  15.9531   56.6800   32.0383    ...       72.9210
2014-01-24   400.2000  15.6077   56.4200   33.2975    ...       71.5955
2014-01-27   394.1000  15.4397   54.9401   32.7122    ...       72.1763
2014-01-28   394.7400  15.6451   55.2800   32.2689    ...       66.4074
2014-01-29   392.8500  15.7291   54.9500   32.7034    ...       65.6535
2014-01-30   406.2500  15.8598   62.5000   32.7034    ...       65.5266
2014-01-31   375.4500  15.8505   63.3700   33.5990    ...       65.6339
2014-02-03   360.8500  15.7571   63.7700   33.6832    ...       65.7558
2014-02-04   353.9975  15.4584   63.1400   32.9774    ...       66.7077
2014-02-05   349.3700  15.3557   63.1600   32.3398    ...       67.2059
2014-02-06   354.8200  15.6171   62.7800   32.1447    ...       67.5976
2014-02-07   361.8000  15.7571   64.5700   32.4462    ...       68.5433
2014-02-10   365.0000  15.6171   64.4900   32.6324    ...       69.7712
2014-02-11   363.6100  15.7944   65.0000   33.0403    ...       70.6906
2014-02-12   357.7500  15.7851   65.0600   33.3418    ...       70.6853
2014-02-13   357.2000  15.7011   67.3300   33.5724    ...       71.8077
2014-02-14   359.3400  15.6451   67.5800   33.5014    ...       71.7497
2014-02-18   355.7300  15.6264   67.5397   33.7527    ...       72.0135
2014-02-19   354.5400  15.3557   69.0800   33.7259    ...       70.8765
2014-02-20   350.4600  15.2717   70.1100   33.8331    ...       70.0561
2014-02-21   354.1410  15.3884   69.9600   34.2619    ...       69.2780
2014-02-24   353.0000  15.5237   71.4400   33.9269    ...       69.5813
2014-02-25   361.0800  15.4584   71.0000   33.8152    ...       68.8572
...               ...      ...       ...       ...    ...           ...
2018-11-15  1624.8200  27.8145  144.8400  107.8000    ...      191.4100
2018-11-16  1614.4800  27.7350  141.7700  108.8800    ...      193.5300
2018-11-19  1581.1900  27.8643  137.7500  108.5600    ...      185.8600
2018-11-20  1534.7500  27.4168  134.1592  102.9700    ...      176.9800
2018-11-21  1550.0000  27.6057  137.1900  104.4300    ...      176.7800
2018-11-23  1536.2000  27.0190  134.5000  103.8099    ...      172.2900
2018-11-26  1584.8100  27.5759  137.0000  106.6300    ...      174.6200
2018-11-27  1597.6500  27.7449  136.6126  107.3300    ...      174.2400
2018-11-28  1681.4500  28.3118  136.7899  111.3300    ...      180.9400
2018-11-29  1689.9900  28.1924  139.9900  111.1150    ...      179.5500
2018-11-30  1696.0000  28.4709  140.9660  110.9700    ...      178.5800
2018-12-03  1778.3400  28.8736  143.6799  113.4200    ...      184.8200
2018-12-04  1770.3400  28.1626  143.3900  112.6373    ...      176.6900
2018-12-06  1701.0500  26.3200  139.7000  109.2400    ...      174.7200
2018-12-07  1718.9300  26.5400  140.8700  109.4500    ...      168.4900
2018-12-10  1657.9900  25.2300  143.0500  107.9800    ...      169.6000
2018-12-11  1679.4700  25.4000  143.8800  110.9500    ...      168.6300
2018-12-12  1704.9900  24.9900  147.1900  111.2700    ...      169.1000
2018-12-13  1692.1200  24.8200  145.8500  110.8700    ...      170.9500
2018-12-14  1642.5700  24.8700  146.0100  109.2600    ...      165.4800
2018-12-17  1576.1300  24.9300  144.9200  105.8000    ...      163.9400
2018-12-18  1567.5500  25.0900  145.9300  104.5100    ...      166.0700
2018-12-19  1584.5300  25.2400  144.9100  106.8800    ...      160.8900
2018-12-20  1509.5000  24.4250  135.5700  104.3100    ...      156.8300
2018-12-21  1480.0000  24.5100  134.9000  103.0000    ...      150.7300
2018-12-24  1396.0300  23.2100  129.7400   97.9700    ...      146.8300
2018-12-26  1473.1600  24.1750  134.2400  100.6900    ...      157.1700
2018-12-27  1469.0000  24.3700  134.9900  101.1900    ...      156.1500
2018-12-28  1513.4700  24.7500  135.9200  102.4100    ...      156.2300
2018-12-31  1520.7600  24.9700  134.6400  102.4000    ...      157.7400

Attributes                                          volume            \
Symbols        AMZN      BAC       FB      MSFT       AAPL      AMZN
date
2014-01-13   390.98  15.3370   55.910   31.0185   94860843   2846507
2014-01-14   397.54  15.6544   57.740   31.7279   83734371   2340401
2014-01-15   395.87  16.0091   57.600   32.5970   98472619   2678794
2014-01-16   395.80  15.9438   57.190   32.7122   57471330   2602506
2014-01-17   399.61  15.8785   56.300   32.2600  108426689   4508791
2014-01-21   407.05  15.8785   58.510   32.0738   82255544   3122705
2014-01-22   404.54  16.0091   57.510   31.8610   95219334   2069759
2014-01-23   399.87  15.7384   56.630   31.9718  100978346   3026272
2014-01-24   387.60  15.3557   54.450   32.6369  108384437   4513038
2014-01-27   386.28  15.2250   53.550   31.9496  144219152   3944752
2014-01-28   394.43  15.6171   55.140   32.1624  266833581   2901611
2014-01-29   384.20  15.5704   53.530   32.5083  125942796   3399294
2014-01-30   403.01  15.8038   61.080   32.6856  169762789  10900116
2014-01-31   358.69  15.6358   62.570   33.5546  116336444  16181519
2014-02-03   346.15  15.2624   61.480   32.3487  100620772  10290934
2014-02-04   347.95  15.2624   62.750   32.2334   94273543   4821177
2014-02-05   346.45  15.3090   62.190   31.7634   82322156   4439010
2014-02-06   354.59  15.5797   62.160   32.0826   64497223   3340542
2014-02-07   361.08  15.7011   64.320   32.4196   93638601   4347189
2014-02-10   360.87  15.6077   63.548   32.6324   86451022   3451093
2014-02-11   361.79  15.7571   64.851   32.9650   70672252   3225200
2014-02-12   349.25  15.6358   64.450   33.2266   77127064   6599199
2014-02-13   357.20  15.6358   67.330   33.3507   76960156   4181445
2014-02-14   357.35  15.5891   67.090   33.3596   68468036   3524570
2014-02-18   353.65  15.3744   67.300   33.4310   65306248   5000493
2014-02-19   347.38  15.1223   68.060   33.5114   78554420   4175393
2014-02-20   349.80  15.2157   69.630   33.7259   76529103   3496663
2014-02-21   346.76  15.2064   68.590   33.9313   69757247   4212144
2014-02-24   351.78  15.4304   70.780   33.6723   72364950   3647182
2014-02-25   358.32  15.2530   69.850   33.5382   58247350   3747076
...             ...      ...      ...       ...        ...       ...
2018-11-15  1619.44  27.7449  143.850  107.2800   46478801   8427337
2018-11-16  1593.41  27.5958  139.530  108.2900   36928253   6066080
2018-11-19  1512.29  27.5958  131.550  104.6200   41920872   7789981
2018-11-20  1495.46  27.2278  132.430  101.7100   67825247  10878823
2018-11-21  1516.73  27.1184  134.820  103.1100   31124210   5716800
2018-11-23  1502.06  26.8201  131.730  103.0700   23623972   2707642
2018-11-26  1581.33  27.4068  136.380  106.4700   44998520   6257716
2018-11-27  1581.42  27.5858  135.000  107.1400   41387377   5783227
2018-11-28  1677.75  28.2720  136.760  111.1200   46062539   8458738
2018-11-29  1673.57  27.8842  138.680  110.1900   41769992   6613243
2018-11-30  1690.17  28.2422  140.610  110.8900   39531549   5761761
2018-12-03  1772.36  28.3814  141.090  112.0900   40798002   6862160
2018-12-04  1668.40  26.8400  137.930  108.5200   41344282   8694455
2018-12-06  1699.19  26.2800  139.630  109.1900   43098410   8789394
2018-12-07  1629.13  25.4300  137.420  104.8200   42281631   7576132
2018-12-10  1641.03  24.7600  141.850  107.5900   62025994   7494808
2018-12-11  1643.24  24.5800  142.080  108.5900   47281665   6244695
2018-12-12  1663.54  24.5200  144.500  109.0800   35627674   6597968
2018-12-13  1658.38  24.4000  145.010  109.4500   31897827   5271162
2018-12-14  1591.91  24.4800  144.060  106.0300   40703710   6367163
2018-12-17  1520.91  24.4700  140.190  102.8900   44287922   8829762
2018-12-18  1551.48  24.4700  143.660  103.9700   33841518   6522975
2018-12-19  1495.08  24.1800  133.240  103.6900   49047297   8792189
2018-12-20  1460.83  24.1100  133.400  101.5100   64772960   9991833
2018-12-21  1377.45  23.3700  124.950   98.2300   95744384  13640320
2018-12-24  1343.96  22.7300  124.060   94.1300   37169232   7219996
2018-12-26  1470.90  24.1100  134.180  100.5600   58582544  10411801
2018-12-27  1461.64  24.3700  134.520  101.1800   53117065   9722034
2018-12-28  1478.02  24.3900  133.200  100.3900   42291424   8828950
2018-12-31  1501.97  24.6400  131.090  101.5700   35003466   6954507

Attributes
Symbols           BAC         FB       MSFT
date
2014-01-13   90827849   63106519   45923872
2014-01-14   98517898   37590987   41627325
2014-01-15  330005943   33730619   44909545
2014-01-16  163879260   34599775   38035708
2014-01-17   96509703   40883205   46298736
2014-01-21  118388995   48734147   31578979
2014-01-22   68231534   61495880   21965266
2014-01-23  124037063   47996403   44515126
2014-01-24  114269725   55545338   77051806
2014-01-27  135060624   74142331   44485767
2014-01-28   93652513   48364998   36225755
2014-01-29  130381992   98089932   52790351
2014-01-30   91147776  150438699   35111959
2014-01-31  139608553   87930298   93190755
2014-02-03  160718806   75105994   64102391
2014-02-04  125833754   46064897   55526924
2014-02-05  110835126   53032420   55841097
2014-02-06  110229403   42153754   35380994
2014-02-07  151911622   60835746   33348008
2014-02-10   96136622   43736562   26782083
2014-02-11   92866298   45746832   32164989
2014-02-12   97286498   47409857   27055869
2014-02-13   96047289   62013396   37647772
2014-02-14  113375071   36786427   42986738
2014-02-18  122179187   43862297   32839707
2014-02-19  138080546   64258631   29794084
2014-02-20  107820954  131043748   27541038
2014-02-21  106622165   70991892   38030656
2014-02-24  103039579   76951946   32143395
2014-02-25   81617640   52189031   30867657
...               ...        ...        ...
2018-11-15   66174810   30320280   38505165
2018-11-16   52456146   37250560   33502121
2018-11-19   45999950   44362729   44773899
2018-11-20   92330608   41939475   64052457
2018-11-21   40364427   25469735   28130621
2018-11-23   22974139   11886128   13823099
2018-11-26   53210681   24263640   32336165
2018-11-27   43617082   20750318   29124486
2018-11-28   61388131   29847505   46788461
2018-11-29   46824634   24238713   28123195
2018-11-30   64284619   25732577   33665624
2018-12-03   59905121   24819226   34732772
2018-12-04  103565701   30307400   45196984
2018-12-06  133294174   28218145   49107431
2018-12-07  107477614   21195460   45044937
2018-12-10  110166901   26422173   40801525
2018-12-11   78545015   20300349   42381947
2018-12-12   87191846   23696936   36183020
2018-12-13   64860054   18148610   31333362
2018-12-14   92762595   21785820   47043136
2018-12-17   98602808   24333959   56957314
2018-12-18   89046306   24709084   49319196
2018-12-19  121887605   57404894   68198186
2018-12-20  112594029   40297944   70334184
2018-12-21  160800438   56901491  111242070
2018-12-24   64859064   22066002   43935192
2018-12-26  100877810   39723370   51634793
2018-12-27   91575402   31202509   49498509
2018-12-28   78693797   22627569   38169312
2018-12-31   56257342   24625308   33173765

[1251 rows x 25 columns]>

In [10]:
p.describe()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th>Attributes</th>
      <th colspan="5" halign="left">open</th>
      <th colspan="5" halign="left">high</th>
      <th>...</th>
      <th colspan="5" halign="left">close</th>
      <th colspan="5" halign="left">volume</th>
    </tr>
    <tr>
      <th>Symbols</th>
      <th>AAPL</th>
      <th>AMZN</th>
      <th>BAC</th>
      <th>FB</th>
      <th>MSFT</th>
      <th>AAPL</th>
      <th>AMZN</th>
      <th>BAC</th>
      <th>FB</th>
      <th>MSFT</th>
      <th>...</th>
      <th>AAPL</th>
      <th>AMZN</th>
      <th>BAC</th>
      <th>FB</th>
      <th>MSFT</th>
      <th>AAPL</th>
      <th>AMZN</th>
      <th>BAC</th>
      <th>FB</th>
      <th>MSFT</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>...</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1251.000000</td>
      <td>1.251000e+03</td>
      <td>1.251000e+03</td>
      <td>1.251000e+03</td>
      <td>1.251000e+03</td>
      <td>1.251000e+03</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>127.024251</td>
      <td>826.217742</td>
      <td>19.864793</td>
      <td>120.795495</td>
      <td>60.939987</td>
      <td>128.115505</td>
      <td>834.178827</td>
      <td>20.046303</td>
      <td>122.010667</td>
      <td>61.454893</td>
      <td>...</td>
      <td>127.038842</td>
      <td>825.635516</td>
      <td>19.854578</td>
      <td>120.818287</td>
      <td>60.948147</td>
      <td>4.274528e+07</td>
      <td>4.243630e+06</td>
      <td>8.492737e+07</td>
      <td>2.874706e+07</td>
      <td>3.083822e+07</td>
    </tr>
    <tr>
      <th>std</th>
      <td>39.057695</td>
      <td>478.205746</td>
      <td>6.148092</td>
      <td>41.112825</td>
      <td>23.245793</td>
      <td>39.412923</td>
      <td>483.116699</td>
      <td>6.198078</td>
      <td>41.424891</td>
      <td>23.456836</td>
      <td>...</td>
      <td>39.037532</td>
      <td>477.220958</td>
      <td>6.141775</td>
      <td>41.163079</td>
      <td>23.201891</td>
      <td>2.352239e+07</td>
      <td>2.404019e+06</td>
      <td>3.924664e+07</td>
      <td>1.936763e+07</td>
      <td>1.529231e+07</td>
    </tr>
    <tr>
      <th>min</th>
      <td>64.923300</td>
      <td>284.400000</td>
      <td>10.907000</td>
      <td>54.020000</td>
      <td>30.796900</td>
      <td>65.755800</td>
      <td>290.420000</td>
      <td>10.992600</td>
      <td>54.940100</td>
      <td>31.816600</td>
      <td>...</td>
      <td>65.526600</td>
      <td>286.950000</td>
      <td>10.621500</td>
      <td>53.530000</td>
      <td>31.018500</td>
      <td>1.147592e+07</td>
      <td>1.092970e+06</td>
      <td>1.427357e+07</td>
      <td>5.913066e+06</td>
      <td>7.425603e+06</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>98.267850</td>
      <td>392.920000</td>
      <td>14.981950</td>
      <td>80.520000</td>
      <td>42.182650</td>
      <td>99.823050</td>
      <td>398.960000</td>
      <td>15.118100</td>
      <td>81.360000</td>
      <td>42.533700</td>
      <td>...</td>
      <td>98.506600</td>
      <td>392.805000</td>
      <td>14.942650</td>
      <td>80.670000</td>
      <td>42.244650</td>
      <td>2.655332e+07</td>
      <td>2.720876e+06</td>
      <td>5.972874e+07</td>
      <td>1.674395e+07</td>
      <td>2.171647e+07</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>113.949200</td>
      <td>730.000000</td>
      <td>16.341700</td>
      <td>117.860000</td>
      <td>52.275700</td>
      <td>114.495800</td>
      <td>739.550000</td>
      <td>16.473800</td>
      <td>118.700000</td>
      <td>52.636000</td>
      <td>...</td>
      <td>113.836800</td>
      <td>735.440000</td>
      <td>16.341700</td>
      <td>117.790000</td>
      <td>52.377700</td>
      <td>3.686854e+07</td>
      <td>3.586323e+06</td>
      <td>7.590151e+07</td>
      <td>2.255892e+07</td>
      <td>2.733446e+07</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>156.263750</td>
      <td>1006.500000</td>
      <td>24.584900</td>
      <td>156.520000</td>
      <td>73.565650</td>
      <td>157.544850</td>
      <td>1010.860000</td>
      <td>24.855800</td>
      <td>158.910000</td>
      <td>73.971550</td>
      <td>...</td>
      <td>156.190000</td>
      <td>1003.370000</td>
      <td>24.511600</td>
      <td>155.750000</td>
      <td>73.609700</td>
      <td>5.201089e+07</td>
      <td>4.863038e+06</td>
      <td>9.963195e+07</td>
      <td>3.348988e+07</td>
      <td>3.512956e+07</td>
    </tr>
    <tr>
      <th>max</th>
      <td>229.977600</td>
      <td>2038.110000</td>
      <td>32.496200</td>
      <td>215.715000</td>
      <td>114.923600</td>
      <td>232.658200</td>
      <td>2050.500000</td>
      <td>32.575100</td>
      <td>218.620000</td>
      <td>115.680300</td>
      <td>...</td>
      <td>231.263100</td>
      <td>2039.510000</td>
      <td>32.368100</td>
      <td>217.500000</td>
      <td>115.112800</td>
      <td>2.668336e+08</td>
      <td>2.385606e+07</td>
      <td>3.750886e+08</td>
      <td>1.698037e+08</td>
      <td>2.025265e+08</td>
    </tr>
  </tbody>
</table>
<p>8 rows × 25 columns</p>
</div>

In [11]:
p.index

Index(['2014-01-13', '2014-01-14', '2014-01-15', '2014-01-16', '2014-01-17',
       '2014-01-21', '2014-01-22', '2014-01-23', '2014-01-24', '2014-01-27',
       ...
       '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21',
       '2018-12-24', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-31'],
      dtype='object', name='date', length=1251)

In [18]:
p.columns

MultiIndex(levels=[['open', 'high', 'low', 'close', 'volume'], ['AAPL', 'AMZN', 'BAC', 'FB', 'MSFT']],
           labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
           names=['Attributes', 'Symbols'])

In [19]:
p.axes

[Index(['2014-01-13', '2014-01-14', '2014-01-15', '2014-01-16', '2014-01-17',
        '2014-01-21', '2014-01-22', '2014-01-23', '2014-01-24', '2014-01-27',
        ...
        '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21',
        '2018-12-24', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-31'],
       dtype='object', name='date', length=1251),
 MultiIndex(levels=[['open', 'high', 'low', 'close', 'volume'], ['AAPL', 'AMZN', 'BAC', 'FB', 'MSFT']],
            labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
            names=['Attributes', 'Symbols'])]